### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by robertmarney** [enlightn/enlightn#127]
### Versions

* PHP version: v8.1
* Laravel version: v9.20
* Enlightn version: v2.1
* Enlightn Pro version (if applicable): v2.2

### Description

When trigger enlightn checks from Windows I am receiving an 'Unable to launch a new process' warning triggered at line 349 of symfony's Process.php

### Steps to Reproduce

Run most checks, including all that use phpstan

php artisan enlightn Enlightn\Enlightn\Analyzers\Reliability\InvalidMethodCallAnalyzer -v

**Expected behavior:**

Enlightn runs

**Actual behavior:**

![image](https://user-images.githubusercontent.com/48888686/179578373-4125fa9c-72cc-4677-b137-db7b05dc95e7.png)

### Additional Information

This code base allows running on Linux environments without issue. Via windows I am able to execute the project fully.

![image](https://user-images.githubusercontent.com/48888686/179578237-77e4734e-fd28-43fa-9dc2-153a629697f8.png)

I am also able to run (via windows) phpstan directly.

**Comment by paras-malhotra** [comment]
Enlightn is not fully compatible with Windows yet. Can you share the full exception using the `--show-exceptions` flag?

**Comment by puyt** [comment]
I'm having the same issue on a Linux machine using Docker, it only happens for the `CollectionCallAnalyzer` check.

```bash
php artisan enlightn --ci Enlightn\\Enlightn\\Analyzers\\Performance\\CollectionCallAnalyzer --show-exceptions

    ______      ___       __    __
   / ____/___  / (_)___ _/ /_  / /_____
  / __/ / __ |/ / / __  / __ |/ __/ __ |
 / /___/ / / / / / /_/ / / / / /_/ / / /
/_____/_/ /_/_/_/\__, /_/ /_/\__/_/ /_/
                /____/


Please wait while Enlightn scans your code base...

|------------------------------------------
| Running Performance Checks
|------------------------------------------

Check 1/1: Aggregation is done at the database query level rather than at the Laravel Collection level. Exception
Unable to launch a new process.
#0 /app/vendor/symfony/process/Process.php(250): Symfony\Component\Process\Process->start()
#1 /app/vendor/enlightn/enlightn/src/PHPStan.php(161): Symfony\Component\Process\Process->run()
#2 /app/vendor/enlightn/enlightn/src/PHPStan.php(141): Enlightn\Enlightn\PHPStan->runCommand()
#3 /app/vendor/enlightn/enlightn/src/EnlightnServiceProvider.php(53): Enlightn\Enlightn\PHPStan->start()
#4 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1302): Enlightn\Enlightn\EnlightnServiceProvider->Enlightn\Enlightn\{closure}()
#5 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1266): Illuminate\Container\Container->fireCallbackArray()
#6 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1252): Illuminate\Container\Container->fireAfterResolvingCallbacks()
#7 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate\Container\Container->fireResolvingCallbacks()
#8 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve()
#9 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#10 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make()
#11 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\Foundation\Application->make()
#12 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\Container\BoundMethod::addDependencyForCallParameter()
#13 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::getMethodDependencies()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#18 /app/vendor/enlightn/enlightn/src/Analyzers/Analyzer.php(116): Illuminate\Container\Container->call()
#19 /app/vendor/enlightn/enlightn/src/Enlightn.php(108): Enlightn\Enlightn\Analyzers\Analyzer->run()
#20 /app/vendor/enlightn/enlightn/src/Console/EnlightnCommand.php(101): Enlightn\Enlightn\Enlightn::run()
#21 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Enlightn\Enlightn\Console\EnlightnCommand->handle()
#22 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#24 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#25 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#26 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#27 /app/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#28 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#29 /app/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#30 /app/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#31 /app/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#32 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#33 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#34 {main}
Documentation URL: https://www.laravel-enlightn.com/docs/performance/collection-call-analyzer.html
```
